name: Strip PR HTML comments

on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  strip:
    permissions:
      contents: read
      pull-requests: write
    uses: jaeyeom/experimental/.github/workflows/strip-pr-html-comments.yml@4176fa4121d4d7c8742debad25af6f85b97ef937
